import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { generateSHA256Hash } from "@/lib/hash";
import { findRecordByHash } from "@/lib/ledger";

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.email) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let fileText: string;

  try {
    const formData = await req.formData();
    const file = formData.get("file") as File | null;

    if (!file) {
      return NextResponse.json({ error: "No file uploaded" }, { status: 400 });
    }

    if (!file.name.endsWith(".json")) {
      return NextResponse.json({ error: "Only .json files are supported" }, { status: 400 });
    }

    fileText = await file.text();
  } catch {
    return NextResponse.json({ error: "Failed to read uploaded file" }, { status: 400 });
  }

  let parsedContent: unknown;

  try {
    parsedContent = JSON.parse(fileText);
  } catch {
    return NextResponse.json({ error: "Invalid JSON file" }, { status: 400 });
  }

  if (
    typeof parsedContent !== "object" ||
    parsedContent === null ||
    !("entries" in parsedContent)
  ) {
    return NextResponse.json({ error: "Invalid log format" }, { status: 400 });
  }

  const fileHash = generateSHA256Hash(parsedContent);
  const record = await findRecordByHash(fileHash);

  if (!record) {
    return NextResponse.json({
      verified: false,
      tampered: true,
      fileHash,
      message: "No matching record found. File is tampered or not generated by this system.",
    });
  }

  return NextResponse.json({
    verified: true,
    tampered: false,
    fileHash,
    storedHash: record.fileHash,
    recordId: record.recordId,
    fileName: record.fileName,
    machineId: record.machineId,
    owner: record.owner ?? "unknown",
    timestamp: record.timestamp,
    entries: record.entries,
    onChain: record.onChain,
    txHash: record.txHash ?? null,
    message: "Integrity verified — file matches original record.",
  });
}